# Generated by Django 4.0.6 on 2022-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('articulo', models.CharField(max_length=30)),
                ('codigoColor', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('cantidadConos', models.IntegerField()),
                ('fechaTenido', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('clienteTenido1', models.CharField(max_length=50)),
                ('clienteTenido2', models.CharField(max_length=50)),
                ('clienteTenido3', models.CharField(max_length=50)),
                ('clienteTenido4', models.CharField(max_length=50)),
                ('clienteTenido5', models.CharField(max_length=50)),
                ('clienteEntrega1', models.CharField(max_length=50)),
                ('kgEntrega1', models.IntegerField()),
                ('conosEntrega1', models.IntegerField()),
                ('fechaEntrega1', models.DateField()),
                ('clienteEntrega2', models.CharField(max_length=50)),
                ('kgEntrega2', models.IntegerField()),
                ('conosEntrega2', models.IntegerField()),
                ('fechaEntrega2', models.DateField()),
                ('clienteEntrega3', models.CharField(max_length=50)),
                ('kgEntrega3', models.IntegerField()),
                ('conosEntrega3', models.IntegerField()),
                ('fechaEntrega3', models.DateField()),
                ('clienteEntrega4', models.CharField(max_length=50)),
                ('kgEntrega4', models.IntegerField()),
                ('conosEntrega4', models.IntegerField()),
                ('fechaEntrega4', models.DateField()),
                ('clienteEntrega5', models.CharField(max_length=50)),
                ('kgEntrega5', models.IntegerField()),
                ('conosEntrega5', models.IntegerField()),
                ('fechaEntrega5', models.DateField()),
                ('clienteEntrega6', models.CharField(max_length=50)),
                ('kgEntrega6', models.IntegerField()),
                ('conosEntrega6', models.IntegerField()),
                ('fechaEntrega6', models.DateField()),
                ('clienteEntrega7', models.CharField(max_length=50)),
                ('kgEntrega7', models.IntegerField()),
                ('conosEntrega7', models.IntegerField()),
                ('fechaEntrega7', models.DateField()),
                ('clienteEntrega8', models.CharField(max_length=50)),
                ('kgEntrega8', models.IntegerField()),
                ('conosEntrega8', models.IntegerField()),
                ('fechaEntrega8', models.DateField()),
                ('clienteEntrega9', models.CharField(max_length=50)),
                ('kgEntrega9', models.IntegerField()),
                ('conosEntrega9', models.IntegerField()),
                ('fechaEntrega9', models.DateField()),
                ('clienteEntrega10', models.CharField(max_length=50)),
                ('kgEntrega10', models.IntegerField()),
                ('conosEntrega10', models.DateField()),
                ('fechaEntrega10', models.CharField(max_length=10)),
            ],
        ),
    ]
