# Generated by Django 4.0.6 on 2022-08-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('articulo', models.CharField(max_length=30)),
                ('codigoColor', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('cantidadConos', models.IntegerField()),
                ('fechaTenido', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('clienteTenido1', models.CharField(max_length=50)),
                ('clienteTenido2', models.CharField(max_length=50)),
                ('clienteTenido3', models.CharField(max_length=50)),
                ('clienteTenido4', models.CharField(max_length=50)),
                ('clienteTenido5', models.CharField(max_length=50)),
            ],
        ),
    ]
