
from django import forms

class FormularioCliente(forms.Form):
    razonSocial = forms.CharField()
    cuit = forms.CharField()
    direccion = forms.CharField()
    provincia = forms.CharField()
    codigoPostal = forms.IntegerField()

class FormularioFabrica(forms.Form):
    razonSocial = forms.CharField()
    cuit = forms.CharField()
    direccion = forms.CharField()
    provincia = forms.CharField()
    codigoPostal = forms.IntegerField()

class FormularioHilado(forms.Form):
    partida = forms.IntegerField()
    kg = forms.IntegerField() 
    cantidadConos = forms.IntegerField()
    fechaTenido = forms.CharField() 
    estado =  forms.CharField() 
    clienteTenido1 = forms.CharField() 
    clienteTenido2 = forms.CharField()
    clienteTenido3 = forms.CharField()
    clienteTenido4 = forms.CharField()
    clienteTenido5 = forms.CharField()
    ordenPedido = forms.IntegerField()
    articulo = forms.IntegerField()    
    codigoColor = forms.IntegerField()  
    clienteEntrega1 = forms.CharField()
    kgEntrega1 = forms.IntegerField() 
    conosEntrega1 = forms.IntegerField() 
    fechaEntrega1 = forms.CharField() 
    clienteEntrega2 = forms.CharField() 
    kgEntrega2 = forms.IntegerField() 
    conosEntrega2 = forms.IntegerField() 
    fechaEntrega2 = forms.CharField() 
    clienteEntrega3 = forms.CharField() 
    kgEntrega3 = forms.IntegerField() 
    conosEntrega3 = forms.IntegerField() 
    fechaEntrega3 = forms.CharField() 
    clienteEntrega4 = forms.CharField() 
    kgEntrega4 = forms.IntegerField() 
    conosEntrega4 = forms.IntegerField() 
    fechaEntrega4 = forms.CharField() 
    clienteEntrega5 = forms.CharField() 
    kgEntrega5 = forms.IntegerField()   
    conosEntrega5 = forms.IntegerField() 
    fechaEntrega5 = forms.CharField() 
    clienteEntrega6 = forms.CharField() 
    kgEntrega6 = forms.IntegerField() 
    conosEntrega6 = forms.IntegerField() 
    fechaEntrega6 = forms.CharField() 
    clienteEntrega7 = forms.CharField() 
    kgEntrega7 = forms.IntegerField() 
    conosEntrega7 = forms.IntegerField() 
    fechaEntrega7 = forms.CharField() 
    clienteEntrega8 = forms.CharField() 
    kgEntrega8 = forms.IntegerField() 
    conosEntrega8 = forms.IntegerField() 
    fechaEntrega8 = forms.CharField() 
    clienteEntrega9 = forms.CharField() 
    kgEntrega9 = forms.IntegerField() 
    conosEntrega9 = forms.IntegerField() 
    fechaEntrega9 = forms.CharField() 
    clienteEntrega10 = forms.CharField() 
    kgEntrega10 = forms.IntegerField() 
    conosEntrega10 = forms.IntegerField() 
    fechaEntrega10 = forms.CharField() 
